CREATE TABLE IF NOT EXISTS `book_source_file` (
  `id`             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '原始文件主键ID',
  `file_key`       VARCHAR(64)     NOT NULL                COMMENT '原始文件业务主键',
  `original_name`  VARCHAR(255)    NOT NULL                COMMENT '上传时的原始文件名',
  `storage_url`    VARCHAR(512)    NOT NULL DEFAULT ''     COMMENT '原始文件在对象存储中的访问地址',
  `file_size`      BIGINT UNSIGNED NOT NULL DEFAULT 0      COMMENT '原始文件字节数',
  `file_hash`      VARCHAR(128)    NOT NULL DEFAULT ''     COMMENT '原始文件哈希值',
  `created_at`     DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_book_source_file_key` (`file_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='书籍导入原始文件表';

CREATE TABLE IF NOT EXISTS `book` (
  `id`             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '书籍主键ID',
  `book_key`       VARCHAR(64)     NOT NULL                COMMENT '书籍业务主键',
  `title`          VARCHAR(255)    NOT NULL                COMMENT '书籍标题',
  `author`         VARCHAR(128)    NOT NULL DEFAULT ''     COMMENT '作者名称',
  `translator`     VARCHAR(128)    NOT NULL DEFAULT ''     COMMENT '译者名称',
  `publisher`      VARCHAR(128)    NOT NULL DEFAULT ''     COMMENT '出版社名称',
  `category`       VARCHAR(64)     NOT NULL DEFAULT '书籍' COMMENT '书籍分类',
  `summary`        TEXT            NOT NULL                COMMENT '书籍简介',
  `cover_url`      VARCHAR(512)    NOT NULL DEFAULT ''     COMMENT '封面地址',
  `tag_list`       VARCHAR(1000)   NOT NULL DEFAULT ''     COMMENT '竖线分隔的标签列表',
  `word_count`     INT UNSIGNED    NOT NULL DEFAULT 0      COMMENT '总字数',
  `chapter_count`  INT UNSIGNED    NOT NULL DEFAULT 0      COMMENT '章节数',
  `read_count`     INT UNSIGNED    NOT NULL DEFAULT 0      COMMENT '阅读人数',
  `rating`         DECIMAL(4,1)    NOT NULL DEFAULT 9.0    COMMENT '评分展示值',
  `status`         TINYINT         NOT NULL DEFAULT 0      COMMENT '状态：0草稿，1发布，-1下线',
  `sort_order`     INT             NOT NULL DEFAULT 0      COMMENT '排序值',
  `published_at`   DATETIME        NULL                    COMMENT '发布时间',
  `created_at`     DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at`     DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_book_key` (`book_key`),
  KEY `idx_book_status_publish` (`status`, `published_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='书籍主表';

CREATE TABLE IF NOT EXISTS `book_chapter` (
  `id`             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '章节主键ID',
  `chapter_key`    VARCHAR(64)     NOT NULL                COMMENT '章节业务主键',
  `book_key`       VARCHAR(64)     NOT NULL                COMMENT '所属书籍业务主键',
  `chapter_no`     INT UNSIGNED    NOT NULL DEFAULT 1      COMMENT '章节序号',
  `title`          VARCHAR(255)    NOT NULL                COMMENT '章节标题',
  `subtitle`       VARCHAR(255)    NOT NULL DEFAULT ''     COMMENT '章节副标题',
  `content_html`   MEDIUMTEXT      NOT NULL                COMMENT '章节富文本正文',
  `word_count`     INT UNSIGNED    NOT NULL DEFAULT 0      COMMENT '章节字数',
  `is_free`        TINYINT(1)      NOT NULL DEFAULT 1      COMMENT '是否免费章节',
  `status`         TINYINT         NOT NULL DEFAULT 0      COMMENT '状态：0草稿，1发布，-1下线',
  `sort_order`     INT             NOT NULL DEFAULT 0      COMMENT '目录排序值',
  `created_at`     DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at`     DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_book_chapter_key` (`chapter_key`),
  KEY `idx_book_chapter_book_sort` (`book_key`, `sort_order`),
  KEY `idx_book_chapter_book_status` (`book_key`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='书籍章节表';

CREATE TABLE IF NOT EXISTS `book_import_job` (
  `id`               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '导入任务主键ID',
  `job_key`          VARCHAR(64)     NOT NULL                COMMENT '导入任务业务主键',
  `book_key`         VARCHAR(64)     NOT NULL DEFAULT ''     COMMENT '解析出的书籍业务主键',
  `title`            VARCHAR(255)    NOT NULL DEFAULT ''     COMMENT '解析出的书籍标题',
  `author`           VARCHAR(128)    NOT NULL DEFAULT ''     COMMENT '解析出的作者名称',
  `translator`       VARCHAR(128)    NOT NULL DEFAULT ''     COMMENT '解析出的译者名称',
  `publisher`        VARCHAR(128)    NOT NULL DEFAULT ''     COMMENT '解析出的出版社名称',
  `summary`          TEXT            NULL                    COMMENT '解析出的书籍简介',
  `category`         VARCHAR(64)     NOT NULL DEFAULT '书籍' COMMENT '书籍分类',
  `cover_url`        VARCHAR(512)    NOT NULL DEFAULT ''     COMMENT '解析出的封面地址',
  `source_file_key`  VARCHAR(64)     NOT NULL DEFAULT ''     COMMENT '原始文件业务主键',
  `import_type`      VARCHAR(32)     NOT NULL DEFAULT 'zip'  COMMENT '导入类型',
  `source_url`       VARCHAR(1024)   NOT NULL DEFAULT ''     COMMENT '外部资源URL',
  `original_format`  VARCHAR(32)     NOT NULL DEFAULT ''     COMMENT '原始文件格式(epub/pdf/txt/md/docx/html/zip)',
  `file_size`        BIGINT UNSIGNED NOT NULL DEFAULT 0      COMMENT '上传文件字节数',
  `status`           VARCHAR(32)     NOT NULL DEFAULT 'uploaded' COMMENT '任务状态',
  `progress`         INT UNSIGNED    NOT NULL DEFAULT 0      COMMENT '进度百分比',
  `total_chapters`   INT UNSIGNED    NOT NULL DEFAULT 0      COMMENT '章节总数',
  `success_chapters` INT UNSIGNED    NOT NULL DEFAULT 0      COMMENT '成功解析章节数',
  `fail_chapters`    INT UNSIGNED    NOT NULL DEFAULT 0      COMMENT '失败章节数',
  `message`          VARCHAR(500)    NOT NULL DEFAULT ''     COMMENT '任务说明或错误信息',
  `created_at`       DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at`       DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_book_import_job_key` (`job_key`),
  KEY `idx_book_import_job_status_time` (`status`, `updated_at`),
  KEY `idx_book_import_job_type_status` (`import_type`, `status`, `updated_at` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='书籍导入任务表';

CREATE TABLE IF NOT EXISTS `book_import_chapter_stage` (
  `id`               BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '暂存章节主键ID',
  `job_key`          VARCHAR(64)     NOT NULL                COMMENT '所属导入任务业务主键',
  `temp_chapter_key` VARCHAR(64)     NOT NULL                COMMENT '暂存章节业务主键',
  `source_path`      VARCHAR(255)    NOT NULL DEFAULT ''     COMMENT '章节源文件路径',
  `chapter_no`       INT UNSIGNED    NOT NULL DEFAULT 1      COMMENT '章节序号',
  `title`            VARCHAR(255)    NOT NULL                COMMENT '章节标题',
  `subtitle`         VARCHAR(255)    NOT NULL DEFAULT ''     COMMENT '章节副标题',
  `content_html`     MEDIUMTEXT      NOT NULL                COMMENT '预处理后的章节正文',
  `plain_text`       MEDIUMTEXT      NOT NULL                COMMENT '章节纯文本内容',
  `word_count`       INT UNSIGNED    NOT NULL DEFAULT 0      COMMENT '章节字数',
  `warning_json`     MEDIUMTEXT      NULL                    COMMENT '预处理告警信息JSON',
  `review_status`    VARCHAR(32)     NOT NULL DEFAULT 'parsed' COMMENT '审核状态',
  `sort_order`       INT             NOT NULL DEFAULT 0      COMMENT '目录排序值',
  `created_at`       DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at`       DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_book_import_stage_key` (`temp_chapter_key`),
  KEY `idx_book_import_stage_job_sort` (`job_key`, `sort_order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='书籍导入章节暂存表';
